const mysql = require('mysql2');
const express = require('express');
const session = require('express-session');
const cors = require('cors');
const path = require('path');
const port = 5000;
const loginData = require('./data/db.json')


const fs = require('fs');
let filedata = fs.readFileSync('./data/db.json');
let userData = JSON.parse(filedata);

const connection = mysql.createConnection({
	host     : 'localhost',
	user     : 'root',
	password : 'password',
	database : 'fuelio'
});

const app = express();
app.use(cors());
//app.use(cors({credentials: true, origin: 'http://localhost:3000'}));
app.use(session({
	secret: 'secret',
	saveUninitialized: false,
    resave: false,
    cookie: {secure: false}
}));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.static(path.join(__dirname, 'static')));




app.get('/', function(request, response) {//ignore for now
	// Render login template
	response.sendFile(path.join(__dirname + '/login'));
});

function testreg(registered) {
	if (registered == true) {
		return "Account created. (BACKEND)";
	}
	else {
		return "Error";
	}
}

//module.exports = testreg;

app.post('/register', function(request, response){
	let username = request.body.username;
	let password = request.body.password;
    let registered = false;

	if(username && password){
		connection.query(`SELECT * FROM UserCredentials WHERE username = '${username}'`, function(error, results, fields) {
			if(error) throw error;
			
			if (results.length > 0){
				response.send({
                    status: 'Account name is already taken. (FROM BACKEND)'
                });
				console.log("Account name is already taken. (BACKEND)");
			} else {
				try{
					// encrypt password using SHA2-256 hash function
					connection.promise().query(`INSERT INTO UserCredentials (username, password) VALUES('${username}', SHA2('${password}', 256))`);
					registered = true;
					const testreg = testreg(registered);
                    response.status(201).send({
                        status: 'Account created. (FROM BACKEND)',
                        registered
                    });
					console.log("Account created. (BACKEND)");
				}
				catch(err){
					console.log(err);
					console.log("Unexpected error occurred.");
				}
			}
			response.end();
		});	
	}

});

function testlog(loggedin) {
	if (loggedin == true) {
		return "Successfully logged in. (FROM BACKEND)";
	}
	else {
		return "Error";
	}
}
//module.exports = testlog;

app.post('/auth', function(request, response, next) {
    //response.setHeader('Access-Control-Allow-Credentials', 'true')
    //console.log(request.body);

	// Capture the input fields
	let username = request.body.username;
	let password = request.body.password;
    let login;
    let SID;

	// Ensure the input fields exists and are not empty
	if (username && password) {
        console.log("Successfully obtained username and password");
		//Execute SQL query that'll select the account from the database based on the specified username and the password generated by the SHA2-256 hash function
		connection.query(`SELECT * FROM UserCredentials WHERE username = '${username}' AND password = SHA2('${password}', 256)`, function(error, results, fields) {
			// If there is an issue with the query, output the error
			if (error) throw error;
			// If the account exists
			if (results.length > 0) {
				// Authenticate the user
                //loggedin = true;
				request.session.loggedin = true;
				request.session.username = username;
                login = request.session.loggedin;
                SID = request.sessionID;
				const testlog = testlog(request.session.loggedin);

                //request.session.save()
                response.send({
                    status: 'Successfully logged in. (FROM BACKEND)',
                    login,
                    //SID
                });
                console.log("Successfully logged in.");
				//return "Successfully logged in.";
                console.log(`Welcome back, ${request.session.username}!`);
                console.log(request.sessionID)
                response.end();
                //response.status(200).end('OK');
                //response.redirect('http://localhost:3000/profile');
                //response.writeHead(301, {Location: `http://localhost:3000/profile`}).end();

			} else {
				response.send({
                    status: 'Incorrect Username and/or Password! (FROM BACKEND)',
                });
				console.log("Incorrect Username and/or Password! (BACKEND)");
			}			
			response.end();
		});
	} else {
		response.send({
            status: 'Please enter Username and Password! (FROM BACKEND)'
        });
        console.log("Please enter Username and Password! (BACKEND)");
		response.end();
	}
});

function testlogout(out) {
	if (out == false) {
		return "Successfully logged out (FROM BACKEND)";
	}
	else {
		return "Error";
	}
}
//module.exports = testlogout;

app.post('/logout', function(request, response) {
    let login = request.session.loggedin;
    request.session.destroy();
    response.send({
        status: "Successfully logged out (FROM BACKEND)",
        login
    })
    console.log("Successfully logged out (BACKEND)")
	request.session.loggedin = false;
	testlogout(request.session.loggedin);
	//return "Successfully logged out (BACKEND)";
    response.end();
});

function testprof(file) {
	if (file == true) {
		return "Information saved.";
	}
	else {
		return "Error";
	}
}
module.exports = testprof;
var name;
app.post('/profile', function(request, response) {
    //response.setHeader('Access-Control-Allow-Credentials', 'true')
    //console.log(request.body.state);
    console.log(request.session.loggedin)
    console.log(request.sessionID)
	name = request.body.name;
	//request.session.name = name;
	let address = request.body.address;
	let address2 = request.body.address2;
	let city = request.body.city;
	let state = request.body.state;
	let zipcode = request.body.zipcode;

	if (request.session.loggedin) {
		try{
			connection.promise().query(`INSERT INTO ClientInformation (name, address, address2, city, state, zipcode) VALUES('${name}', '${address}', '${address2}', '${city}', '${state}', '${zipcode}') `);
			response.status(201).send({
                status: 'Information saved.' 
            });
			if (connection.promise().query(`SELECT * FROM ClientInformation WHERE ClientInformation.name = VARCHAR()`)) {
				const testprof = testprof(true)
			}

			console.log("Information saved.");
			//return "Client information saved.";
		}
		catch(err){
			console.log(err);
			console.log("Information was not saved.");
		}
	} else {
        response.send({
            status: "Please login to view this page! (FROM BACKEND)"
        })
		console.log("Please login to view this page!");
	}
	response.end();

    
    // if (loggedin == true) {
	// 	// Output username
	// 	response.send('Welcome back, ' + request.session.username + '!');
	// } else {
	// 	// Not logged in
	// 	response.send('Please login to view this page!');
	// }

});

function testfuel(fuel) {
	if (fuel == true) {
		return "Fuel quote form was successfully generated.";
	}
	else {
		return "Error";
	}
}
//module.exports = testfuel;
app.post("/fuelquotemodule", (req, res) => { //retrieve
    console.log('Retrieving data from frontend')
    console.log(req.body);

    const data = req.body;
	let request = req.body.request;
	let date = req.body.date;
	
	let price = req.body.price;
	let cost = req.body.cost;
	let address = req.body.address;
	let address2 = req.body.address2;
	let city = req.body.city;
	let state = req.body.state;
	let zipcode = req.body.zipcode;

	if (request && date) {
		try {
			connection.promise().query(`INSERT INTO FuelQuote (address,address2,city,state,zipcode) SELECT address,address2,city,state,zipcode FROM ClientInformation WHERE name = ?`, [name]);
			connection.promise().query(`INSERT INTO FuelQuote (request,date) VALUES('${request}', '${date}')`);
			//res.status(201).send({msg: 'Created User'});

			console.log("Fuel quote form was successfully generated.");
			if (connection.promise().query(`SELECT * FROM ClientInformation,FuelQuote WHERE ClientInformation.address = FuelQuote.address`)) {
				const testfuel = testfuel(true)
			}
			
			//return "Fuel quote form was successfully generated."
			console.log("BYE2")
		}
		catch (err) {
			console.log(err);
			console.log("Fuel quote form was not generated.");
		}
	}

    //console.log(userData);
    
    userData.push(data)
    fs.writeFile('./data/db.json', JSON.stringify(userData), function (err) {
        if (err) throw err;
    });
    
    res.json({
        status: "Data successfully retrieved",
    });
})

app.post("/pricingmodule", (req, res) => { //retrieve
    
})

app.listen(port, () => {console.log(`Server started on port ${port}`)});


